apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: node-backend
  name: node-backend
spec:
  replicas: 2  # Number of desired replicas (pods)
  selector:
    matchLabels:
      run: node-backend  # Labels to match with pods controlled by this Deployment
  template:
    metadata:
      labels:
        run: node-backend # Labels applied to pods created by this Deployment
    spec:
      containers:
        - image: gcr.io/propane-country-406506/node-backend:latest # Container image to use
          name: node-backend # Name of the container within the pod
          ports:
            - containerPort: 80 # Port on which the container listens
