apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: node-backend
  name: node-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      run: node-backend
  template:
    metadata:
      labels:
        run: node-backend
    spec:
      containers:
      - image: gcr.io/propane-country-406506/node-backend:latest
        name: node-backend
        ports:
        - containerPort: 80